### ISSUE TITLE
More flexible plotting options

### ISSUE THREAD

**Issue by MitchellAcoustics** [vjalby/vijPlots#1]
Thanks for creating this module, it looks great!

There are a few options and choices I'm curious about - 

1. It seems the Likert plotting requires at least two Likert variables to be selected. Why is this? Especially when using a grouping variable, it would be useful to be able to plot one Likert variable at a time. Is this a constraint of the underlying plotting library?
2. It is currently not possible to plot two Likert variables with different labels (but the same ordinal scale). For instance, selecting one variable labelled [Significantly interferes (1) -> Significantly enhances (5)] and another labelled [Very dissatisfied (1) -> Very satisfied (5)] results in a plot which cannot be compared. I understand the issue and default choice here, but it would be nice to have a checkbox option to split responses by the level number [1 -> 5] if available, rather than by the labels so that these can be shown on the same plot.

![image](https://github.com/user-attachments/assets/0d49ad5c-13a7-4be3-ab82-4ae70acca540)

**Comment by vjalby** [comment]
@MitchellAcoustics 

Thanks for your comment.

1. It's actually a limitation from ggstats package I use to build  the chart. I'll ask Joseph @larmarange to see if there's a workaround.
2. I should easily add an option to use the level number instead of label text (if the variable is of type "integer"). I will work at it tonight.

Vincent

**Comment by vjalby** [comment]
@MitchellAcoustics 

I fixed the two points in version 0.7.0, uploaded here. It should be available in jamovi library next week. 

Vincent

**Comment by MitchellAcoustics** [comment]
@vjalby Thanks very much for the quick fix!

**Comment by vjalby** [comment]
Mitchell, I've uploaded a [new version of vijPlots (0.9.6)](https://github.com/vjalby/vijPlots/tree/main/modules). I made many changes to Likert function. I would be great if you could test it before I release it to jamovi library. (It requires jamovi 2.7+) Thanks !
